### ISSUE TITLE
Table rowspans are ignored

### ISSUE THREAD

**Issue by wheelercj** [wheelercj/Stardown#76]
HTML table cells (`th` and `td` elements) can have attributes `colspan` and `rowspan` that allow the cell to span multiple columns and/or rows. Stardown handles colspans well by creating empty cells as needed, but currently ignores rowspans.

**To Reproduce**
1. Go to https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced#tables_for_visually_impaired_users
2. Select the contents of the table
3. Use Stardown to copy the table
4. Paste into an editor
5. See that the first row is correct but the second one is incorrect because the rowspan in the first row was ignored

**Expected behavior**
Empty cells should be added as needed to imitate the rowspans.

**Screenshots**
Here's a screenshot of the selection described above:

![image](https://github.com/wheelercj/Stardown/assets/39012918/5de49ff7-741b-43f0-b71c-289141882a3d)

Between the two horizontal rules below is Stardown's current output for the selection.

---

> [!note]
> from [HTML table advanced features and accessibility - Learn web development | MDN](https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced#:~:text=Sold%20August%202016-,Clothes,19,-But%20what%20if)

**Items Sold August 2016**

|  | | Clothes | | | Accessories | |
| --- | --- | --- | --- | --- | --- | --- |
| Trousers | Skirts | Dresses | Bracelets | Rings |
| Belgium | Antwerp | 56 | 22 | 43 | 72 | 23 |
| Gent | 46 | 18 | 50 | 61 | 15 |
| Brussels | 51 | 27 | 38 | 69 | 28 |
| The Netherlands | Amsterdam | 89 | 34 | 69 | 85 | 38 |
| Utrecht | 80 | 12 | 43 | 36 | 19 |

---

**Additional context**
Note that a single cell can use both the rowspan and colspan attributes. The relevant part of the code to change is in src/tables.js (and there are no tests for this yet, so also test/tables.js). The three cells with rowspans in the example table may be relatively easy to handle since they're on the table's left edge, but Stardown ideally should be able to handle rowspans elsewhere as well.

**Comment by wheelercj** [comment]
Right now, I'm drawing a blank on a simple way to implement this, but I'll keep thinking about it while working on other things.

@chizuo maybe we can talk about this during our next meeting.

**Comment by chizuo** [comment]
@wheelercj can you link me the function that converts a table to MD?

And the line where it deals with rows so I can think of where it is going wrong and what needs to be changed.

**Comment by wheelercj** [comment]
> @wheelercj can you link me the function that converts a table to MD?
> 
> And the line where it deals with rows so I can think of where it is going wrong and what needs to be changed.

Right, the relevant code is below. It's currently using [Turndown](https://github.com/mixmark-io/turndown)'s rule framework. When a table is being converted from HTML to markdown, the tableCell replacement function is called first for each cell in a row. Then the tableRow replacement function runs for that row. Once all rows are converted, the table replacement function runs. Each of these functions has these parameters: a `string` of the element's markdown content, and a `Node` of the element's HTML content.

https://github.com/wheelercj/Stardown/blob/da1d2c07d6cf6f1236c1ae1ceec0482e0aea6e83/src/tables.js#L47-L111

Here are some ideas for how we might solve this, but none of these seem simple to me:

- A global 2-D array of booleans that we gradually build on each tableCell replacement function call to keep track of where the spans are. The array gets reset at the end of the table replacement function call.
- Maybe it's possible to add cells to the table via the `cell` variable (of type `Node`) in the tableCell replacement function.
- We could stop using the Turndown framework for table cells and table rows. With just the table rule, we could rewrite the rest of the code.

I'm sure I could figure this out eventually, but I feel like I might be missing a simple way to solve this.
